name: tag ecr
description: put tag to aws ecr
inputs:
  registry-id:
    description: 'AWS account ID associated with the registry'
    required: true
  repository:
    description: 'ECR repository'
    required: true
  source-tag:
    description: 'The source tag'
    required: true
  add-tag:
    description: 'Tags to add to the source tag'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    AWS_REGISTRY_ID: ${{ inputs.registry-id }}
    REPOSITORY_NAME: ${{ inputs.repository }}
    SOURCE_TAG: ${{ inputs.source-tag }}
    ADD_TAG: ${{ inputs.add-tag }}
