name: kms encrypt
description: aws kms encrypt
inputs:
  file:
    description: 'encrypt file path'
    required: true
  kms-key-alias:
    description: 'kms key alias'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - -f ${{ inputs.file }}
    - -k ${{ inputs.kms-key-alias }}
