name: kms decrypt
description: aws kms decrypt All files named *.encrypted
inputs:
  key-alias:
    description: 'kms key alias'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - -a
    - -k ${{ inputs.key-alias }}
